CREATE DATABASE IF NOT EXISTS osecbd CHARACTER SET utf8 COLLATE utf8_general_ci;
USE osecbd;

DROP TABLE IF EXISTS Test;

SET FOREIGN_KEY_CHECKS=1;

CREATE TABLE IF NOT EXISTS Test (
    id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT
);

INSERT INTO Test(id) VALUES
(null);